# docker build --pull --rm -f ".docker/dockerfile" -t ailaboclient:latest .

FROM nginx:alpine

COPY .docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

COPY .docker/nginx/ssl /etc/nginx/ssl

COPY app/build /usr/share/nginx/build

EXPOSE 80 443